"""empty message

Revision ID: 8942f5aa263a
Revises: 65b97977f37a
Create Date: 2021-04-09 09:48:51.396749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8942f5aa263a'
down_revision = '65b97977f37a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'date_added')
    op.drop_column('Artist', 'date_added')
    # ### end Alembic commands ###
